name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  build:
    uses: ./.github/workflows/build_docker.yml

  test:
    needs: build
    uses: ./.github/workflows/test.yml

  deploy:
    needs: [build, test] 
    uses: ./.github/workflows/deploy.yml


