name: Deploy Job

on:
  workflow_call:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Download Docker image artifact
      uses: actions/download-artifact@v3
      with:
        name: docker-image
        path: artifacts/

    - name: Load Docker image
      run: docker load -i artifacts/my-flask-app.tar

    - name: Log in to Docker Hub
      run: |
        echo "${{ secrets.DOCKER_HUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_HUB_USERNAME }}" --password-stdin

    - name: Tag Docker image for Docker Hub
      run: docker tag my-flask-app:latest ${{ secrets.DOCKER_HUB_USERNAME }}/my-flask-app:latest

    - name: Push Docker image to Docker Hub
      run: docker push ${{ secrets.DOCKER_HUB_USERNAME }}/my-flask-app:latest

    - name: Cleanup local Docker images
      run: docker rmi my-flask-app:latest ${{ secrets.DOCKER_HUB_USERNAME }}/my-flask-app:latest
