name: Test Job

on:
  workflow_call:

jobs:
  test-docker:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Download Docker image artifact
      uses: actions/download-artifact@v3
      with:
        name: docker-image
        path: artifacts/

    - name: Load Docker image
      run: docker load -i artifacts/my-flask-app.tar

    - name: Run Docker container for testing
      run: docker run -d -p 5000:5000 my-flask-app
    - name: Wait for Flask to start
      run: sleep 15
    - name: Verify container is running
      run: |
        curl --fail http://localhost:5000/status || exit 1



